import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThirdwebProviderV4 from "./providers/ThirdwebProviderV4";
import ThirdwebProviderV5 from "./providers/ThirdwebProviderV5";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThirdwebProviderV4>
        <ThirdwebProviderV5>
          <body className={inter.className}>{children}</body>
        </ThirdwebProviderV5>
      </ThirdwebProviderV4>
    </html>
  );
}
